version: '3.9'

services:
  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:${API_PORT}/
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - backend
    restart: on-failure

  backend:
    build: ./backend
    volumes:
      - ./logs:/app/logs
    environment:
      API_KEY: ${API_KEY}
      API_AMQP_URL: ${AMQP_URL}
      API_DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${API_PORT}:8000
    depends_on:
      - rabbitmq
      - postgres
    entrypoint:
      "./wait-for rabbitmq:5672 -- ./wait-for postgres:5432 -- sh ./entrypoint.sh"
    restart: on-failure

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}
    restart: on-failure

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: on-failure
